### ISSUE TITLE
using pycaffe.py to prune the alexnet model, but no performance improved

### ISSUE THREAD

**Issue by xhsoldier** [garion9013/impl-pruning-caffemodel#3]
I downloaded the alexnet from: https://github.com/BVLC/caffe/tree/master/models/bvlc_alexnet

Using the pycaffe.py to prune this net: 
`python pycaffe.py deploy.prototxt bvlc_alexnet.caffemodel alexnet_pruned.caffemodel  `  

Then I use the alexnet_pruned.caffemodel  for predicting the image using caffe python:
```
t_start = time.time()                                                                                                                                                       
output = net.forward()                                                                                                                                                      
t_stop = time.time()                                                                                                                                                        
duration = t_stop - t_start  #performance
```
I have tested in both CPU and GPU mode(caffe.set_mode_cpu() & caffe.set_mode_gpu() ), the performance seems the same.

**Comment by Saniya666** [comment]
Me too!

**Comment by younghwanoh** [comment]
See #4, this repository not fully implements pruning
