### ISSUE TITLE
I have some questions that need to be answered.

### ISSUE THREAD

**Issue by Saniya666** [garion9013/impl-pruning-caffemodel#4]
Hi, I use freeze.py on the VGG model, but the size of output.caffemodel  is the same as the original size. Is this the result right?

**Comment by xhsoldier** [comment]
I guess pruning should accelerate the predicting performance, but the test result is not.

**Comment by Saniya666** [comment]
Maybe. But I don't understand why the output.caffemodel size has not been reduced.

**Comment by younghwanoh** [comment]
Oh, this repository is managed just for my personal loggings.
_freeze.py_ doesn't apply pruning on caffemodel. I've committed this file by mistake.
_pycaffe.py_ or _proto.py_ does pruning but, they don't actually use sparse matrix format.
Thus, you cannot get effective performance from compressed model.
These codes just apply zero to near-zero weights and update the corresponding prototxt files.

If you are interested in reproducing the result of "iterative pruning" papers.
Why don't you visit [the author's repository](https://github.com/songhan/Deep-Compression-AlexNet)?
